# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Create Docker image and Helm chart
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Package jar
      uses: LucaFeger/action-maven-cli@1.1.0
      with:
        args: clean install
    - name: Login to gcloud registry
      id: gcloud
      uses: elgohr/gcloud-login-action@master
      with:
        account_key: ${{ secrets.sa_key }}
    - run: |
        mkdir "dependency"
        (cd dependency || exit; jar -xf ../target/*.jar)
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: eu.gcr.io/covid-270517/covid-cpc-api
        username: ${{ steps.gcloud.outputs.username }}
        password: ${{ steps.gcloud.outputs.password }}
        registry: eu.gcr.io
        tags: ${{ github.ref }}
